platform :ios do
  lane :build_only do
    increment_build_number(
      xcodeproj: "SampleApp.xcodeproj",
      build_number: ENV['BUILD_NUMBER']
    )

    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV['MATCH_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_B64'],
      duration: 1200,
      in_house: false,
      is_key_content_base64: true,
    )

    deploy_env = ENV['DEPLOY_ENVIRONMENT']
    match_type = deploy_env == 'production' ? "appstore" : "adhoc"
    export_method = deploy_env == 'production' ? "app-store" : "ad-hoc"

    UI.message("🔧 Building for #{deploy_env} using match type '#{match_type}' and export method '#{export_method}'")

    match(
      type: match_type,
      api_key: api_key,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV['MATCH_PASSWORD'],
      readonly: true,
      git_url: ENV["MATCH_GIT_URL"]
    )

    build_app(
      project: "SampleApp.xcodeproj",
      scheme: "SampleApp",
      export_method: export_method,
      output_directory: "./build",
      clean: true
    )

    if deploy_env == "staging"
      firebase_app_distribution(
        app: ENV['FIREBASE_APP_ID'],
        ipa_path: "./build/SampleApp.ipa",
        firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
        testers: ENV['TESTERS'],
        release_notes: ENV['RELEASE_NOTE']
      )

    elsif deploy_env == 'production'
      # Option 1: Directly submit to App Store for review and release
      deliver(
        ipa: "./build/SampleApp.ipa",
        api_key: api_key,
        submit_for_review: true, 
        automatic_release: true, 
        skip_metadata: true,
        skip_screenshots: true,
        run_precheck_before_submit: false,
        submission_information: {
          export_compliance_uses_encryption: true,
          export_compliance_is_exempt: true
        }
      )

      # Optionally: If you want to keep TestFlight upload as well
      # upload_to_testflight(
      #   api_key: api_key,
      #   ipa: "./build/SampleApp.ipa"
      # )
    end

    delete_keychain(name: ENV['MATCH_KEYCHAIN_NAME'])
  end
end
