platform :ios do
  lane :build_only do
    create_keychain(
      name: "ci_temp.keychain",
      password: "android",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      type: "development",
      api_key_path: "./api_key.json",
      keychain_name: "ci_temp.keychain",
      keychain_password: "android",
      readonly: true,
      git_url: https://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@github.com/krushna1512/certs.git
    )

    build_app(
      project: "SampleApp.xcodeproj",
      scheme: "SampleApp",
      export_method: "development",
      output_directory: "./build",
      clean: true
    )

    delete_keychain(name: "ci_temp.keychain")
  end
end
