name: Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: List all code signing identities
        run: security find-identity -v -p codesigning

      - name: Setup keychain
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security list-keychains -s "$KEYCHAIN_NAME"
          security default-keychain -s "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security set-keychain-settings -t 3600 -u "$KEYCHAIN_NAME"
        env:
          KEYCHAIN_NAME: build.keychain
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}


      - name: Install bundler and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Decode .p8 file from base64
        env:
          BASE64_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}
          KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        run: |
          mkdir -p ~/private_keys
          echo "$BASE64_KEY" | base64 -d > ~/private_keys/AuthKey_${KEY_ID}.p8

      - name: Run Fastlane
        env:
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        run: bundle exec fastlane build_and_upload

      - name: Show xcodebuild archive error log
        if: failure()
        run: |
          echo "Dumping last 50 lines of xcodebuild log..."
          tail -n 50 ~/Library/Logs/gym/SampleApp-SampleApp.log || echo "Log file not found"
