name: iOS Build (Gym Only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Select Xcode 16
        run: xcode-select -s /Applications/Xcode_15.4.app
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Avoid deprecation warnings from Ruby 3.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          bundle update fastlane  

      - name: Build with Fastlane (gym)
        run: bundle exec fastlane ios build
