name: iOS Build (Gym Only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app || sudo xcode-select -s /Applications/Xcode.app

      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: |
          bundle install || echo "No Gemfile found, skipping bundle install"
          gem install fastlane

      - name: Build with Fastlane (gym)
        run: bundle exec fastlane ios build
