name: iOS Build (Gym Only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Select Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: |
          bundle install || echo "No Gemfile found, skipping bundle install"
          gem install fastlane

      - name: Build with Fastlane (gym)
        run: bundle exec fastlane ios build
