name: staging

on:
  workflow_dispatch:
    inputs:
      BUILD_NUMBER:
        description: 'Please Enter Build Number'
        required: true
      DEPLOY_ENVIRONMENT:
        description: 'Deployment Environment (staging or production)'
        required: true
        default: 'staging'
      RELEASE_NOTE:
        description: 'Release notes'
        required: False


jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install Fastlane Plugins
        run: fastlane install_plugins

      - name: Set up match and build with Fastlane
        env:
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} 
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}
          BUILD_NUMBER: ${{ inputs.BUILD_NUMBER }}
          DEPLOY_ENVIRONMENT: ${{ inputs.DEPLOY_ENVIRONMENT }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          TESTERS: ${{ secrets.TESTERS }}
          RELEASE_NOTE: ${{ inputs.RELEASE_NOTE }}
        run: bundle exec fastlane ios build_only --verbose
