name: test signin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Generate App Store Connect API Key JSON
        run: |
          echo '{
            "key_id": "${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}",
            "issuer_id": "${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID}}",
            "key": "${{ secrets.APP_STORE_CONNECT_API_KEY}}",
            "duration": 1200,
            "in_house": false
          }' > api_key.json

      - name: Setup keychain for Fastlane
        run: |
          security create-keychain -p ${{ secrets.MATCH_PASSWORD }} ${{ secrets.MATCH_KEYCHAIN_NAME }}
          security default-keychain -s ${{ secrets.MATCH_KEYCHAIN_NAME }}
          security unlock-keychain -p ${{ secrets.MATCH_PASSWORD }} ${{ secrets.MATCH_KEYCHAIN_NAME }}
          security set-keychain-settings ${{ secrets.MATCH_KEYCHAIN_NAME }}

      - name: Match development certificate
        run: bundle exec fastlane match development --api_key_path ./api_key.json
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}

      - name: Generate App Store Connect API Key
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}" > AuthKey.p8


      - name: List AuthKey file
        run: ls -l AuthKey.p8
      
      - name: Print AuthKey contents (base64-decoded)
        run: |
          echo "Decoded AuthKey.p8 contents:"
          cat AuthKey.p8

      - name: Set up match and build with Fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} 
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}# if using encrypted repo
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID}}
          APP_STORE_CONNECT_API_KEY_B64: ${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}
        run: bundle exec fastlane ios build_only

      - name: Delete temporary keychain (cleanup)
        if: always()
        run: |
          security delete-keychain ci_temp.keychain
