name: test signin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Fastlane
        run: gem install fastlane

      - name: Generate App Store Connect API Key JSON
        run: |
          echo '{
            "key_id": "5B2TCCH5A5",
            "issuer_id": "69a6de7a-0c96-47e3-e053-5b8c7c11a4d1",
            "key": "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPHaYGDThgZbLNOiN\nM5Kgf/DWScZa77Td7Z0BkXcIIzWgCgYIKoZIzj0DAQehRANCAATwviHhbnKXVYYg\nCTykJ1/f1nzfsLzVeZLTZ/eTBQWaZY65h8XogyR2AsOglZ7HVW5IYCpXPD6kpoz9\nyGpTfliU\n-----END PRIVATE KEY-----",
            "duration": 1200,
            "in_house": false
          }' > api_key.json

      - name: Setup keychain for Fastlane
        run: |
          security create-keychain -p android ci_temp.keychain
          security default-keychain -s ci_temp.keychain
          security unlock-keychain -p android ci_temp.keychain
          security set-keychain-settings ci_temp.keychain

      - name: Match development certificate
        run: bundle exec fastlane match development --api_key_path ./api_key.json
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}

      - name: Write API Key File
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > ./AuthKey.p8


      - name: Generate App Store Connect API Key
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}" > AuthKey.p8

      - name: Set up match and build with Fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} 
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}# if using encrypted repo
        run: bundle exec fastlane ios build_only

      - name: Delete temporary keychain (cleanup)
        if: always()
        run: |
          security delete-keychain ci_temp.keychain
