name: Test Code Signing with Fastlane Match

on:
  workflow_dispatch:

jobs:
  test-code-signing:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Setup keychain
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Install bundler and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Fastlane Match
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          KEYCHAIN_NAME: build.keychain
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          bundle exec fastlane match development --type development --keychain_name "$KEYCHAIN_NAME" --keychain_password "$KEYCHAIN_PASSWORD"

      - name: Show installed code signing identities
        run: |
          security find-identity -v -p codesigning build.keychain

      - name: List installed provisioning profiles
        run: ls -l ~/Library/MobileDevice/Provisioning\ Profiles || echo "No profiles found"
